"""initial schema

Revision ID: 7b3ba0765d56
Revises: 
Create Date: 2026-06-19 23:51:34.283165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b3ba0765d56'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=False),
    sa.Column('cp_type', sa.Text(), nullable=True),
    sa.Column('affected_side', sa.Text(), nullable=True),
    sa.Column('gmfcs_current', sa.Text(), nullable=True),
    sa.Column('dominant_side', sa.Text(), nullable=True),
    sa.Column('comorbidities', sa.Text(), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=True),
    sa.Column('consent_on_file', sa.Boolean(), nullable=False),
    sa.Column('consent_date', sa.Date(), nullable=True),
    sa.Column('guardian_contact', sa.Text(), nullable=True),
    sa.Column('enrollment_date', sa.Date(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sex IN ('M', 'F', 'other', 'unknown')", name='patients_sex_check'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('session_type', sa.Text(), nullable=True),
    sa.Column('session_number', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', 'aborted', name='session_status'), server_default='active', nullable=False),
    sa.Column('passive_calibration_done', sa.Boolean(), nullable=False),
    sa.Column('baseline_force_right', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('baseline_force_left', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sampling_rate_hz', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('patients')
    # ### end Alembic commands ###
