"""add assessments module

Revision ID: 8277fd10ac7c
Revises: 7b3ba0765d56
Create Date: 2026-06-20 00:01:32.545423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8277fd10ac7c'
down_revision: Union[str, Sequence[str], None] = '7b3ba0765d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessments',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('assessment_date', sa.Date(), nullable=True),
    sa.Column('assessment_type', sa.Text(), nullable=True),
    sa.Column('assessment_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_index(op.f('ix_assessments_patient_id'), 'assessments', ['patient_id'], unique=False)
    op.create_table('assessment_body',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('body_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('leg_length_left_m', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('leg_length_right_m', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('assessment_observations',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('toe_walking', sa.Boolean(), nullable=False),
    sa.Column('foot_dragging', sa.Boolean(), nullable=False),
    sa.Column('hip_hiking', sa.Boolean(), nullable=False),
    sa.Column('circumduction', sa.Boolean(), nullable=False),
    sa.Column('crouched_gait', sa.Boolean(), nullable=False),
    sa.Column('scissor_gait', sa.Boolean(), nullable=False),
    sa.Column('reduced_arm_swing', sa.Boolean(), nullable=False),
    sa.Column('uses_aid', sa.Boolean(), nullable=False),
    sa.Column('needs_support', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('assessment_spatial_gait',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('step_length_left_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('step_length_right_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stride_length_left_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stride_length_right_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('step_width_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('step_symmetry_index_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('foot_angle_left', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('foot_angle_right', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    op.create_table('assessment_walking_tests',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('cadence_steps_min', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_10mwt_comfort_ms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('speed_10mwt_fast_ms', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tug_seconds', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('distance_6mwt_m', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_walking_tests')
    op.drop_table('assessment_spatial_gait')
    op.drop_table('assessment_observations')
    op.drop_table('assessment_body')
    op.drop_index(op.f('ix_assessments_patient_id'), table_name='assessments')
    op.drop_table('assessments')
    # ### end Alembic commands ###
