"""add profile json to sessions table

Revision ID: c482e8669c5d
Revises: 22d4c0d49a04
Create Date: 2026-06-24 20:34:50.872688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c482e8669c5d'
down_revision: Union[str, Sequence[str], None] = '22d4c0d49a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('exo_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('sessions', 'sampling_rate_hz')
    op.drop_column('sessions', 'session_type')
    op.drop_column('sessions', 'baseline_force_left')
    op.drop_column('sessions', 'baseline_force_right')
    op.drop_column('sessions', 'passive_calibration_done')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('passive_calibration_done', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('baseline_force_right', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('baseline_force_left', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('session_type', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('sampling_rate_hz', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('sessions', 'ended_at')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'exo_profile')
    # ### end Alembic commands ###
