"""collapse assessment detail tables into form_data jsonb

Revision ID: f1acc08b0151
Revises: c482e8669c5d
Create Date: 2026-07-04 01:18:26.897499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1acc08b0151'
down_revision: Union[str, Sequence[str], None] = 'c482e8669c5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_walking_tests')
    op.drop_table('assessment_body')
    op.drop_table('assessment_spatial_gait')
    op.drop_table('assessment_observations')
    op.add_column('assessments', sa.Column('assessor', sa.Text(), nullable=True))
    op.add_column('assessments', sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'form_data')
    op.drop_column('assessments', 'assessor')
    op.create_table('assessment_observations',
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('toe_walking', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('foot_dragging', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('hip_hiking', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('circumduction', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('crouched_gait', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('scissor_gait', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('reduced_arm_swing', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('uses_aid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('needs_support', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('assessment_observations_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('assessment_observations_pkey'))
    )
    op.create_table('assessment_spatial_gait',
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('step_length_left_cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('step_length_right_cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('stride_length_left_cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('stride_length_right_cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('step_width_cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('step_symmetry_index_pct', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('foot_angle_left', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('foot_angle_right', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('assessment_spatial_gait_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('assessment_spatial_gait_pkey'))
    )
    op.create_table('assessment_body',
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('body_weight_kg', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('height_cm', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('leg_length_left_m', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.Column('leg_length_right_m', sa.NUMERIC(precision=4, scale=3), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('assessment_body_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('assessment_body_pkey'))
    )
    op.create_table('assessment_walking_tests',
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cadence_steps_min', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('speed_10mwt_comfort_ms', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('speed_10mwt_fast_ms', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('tug_seconds', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.Column('distance_6mwt_m', sa.NUMERIC(precision=6, scale=2), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.assessment_id'], name=op.f('assessment_walking_tests_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assessment_id', name=op.f('assessment_walking_tests_pkey'))
    )
    # ### end Alembic commands ###
